import { cn } from "@/utils/classNames";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import Providers from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="dark">
			<body
				className={cn(
					"antialiased text-slate-900 bg-slate-50 dark:text-slate-50 dark:bg-background",
					inter.className
				)}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
