import { cn } from "@/utils/classNames";
import "../styles/globals.css";
import Providers from "@/components/Providers";
import { Inter_Tight } from "next/font/google";
import Header from "@/components/Header";
import { getServerAuthSession } from "@/utils/auth";

const inter = Inter_Tight({
	subsets: ["latin"],
	display: "auto",
	adjustFontFallback: true,
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	preload: true,
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	//get server session
	const session = await getServerAuthSession();

	return (
		<html lang="en">
			<body
				className={cn(
					"antialiased flex flex-col min-h-screen w-full tracking-wider text-background bg-slate-50 dark:bg-background dark:text-slate-50",
					inter.className
				)}
			>
				<Providers session={session}>
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	);
}
