import { cn } from "@/utils/classNames";
import "../styles/globals.css";
import Providers from "@/components/Providers";
import Header from "@/components/Header";
import { Inter_Tight } from "next/font/google";

const inter = Inter_Tight({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={cn(
					"antialiased flex flex-col min-h-screen w-full tracking-wider text-background bg-slate-50 dark:bg-background dark:text-slate-50",
					inter.className
				)}
			>
				<Providers>
					<Header />
					{children}
				</Providers>
			</body>
		</html>
	);
}
